// Activity Approval Statuses
export const PROFILE_APPROVAL_STATUS_DRAFT = -1;
export const PROFILE_APPROVAL_STATUS_AWAITED = 0;
export const PROFILE_APPROVAL_STATUS_APPROVED = 1;
export const PROFILE_APPROVAL_STATUS_EDITED = 2;
export const PROFILE_APPROVAL_STATUS_NEWLY_REJECTED = 3;
export const PROFILE_APPROVAL_STATUS_CHANGES_REJECTED = 4;

export const ENUM_PROFILE_APPROVAL_STATUS = [
  APPROVAL_STATUS_DRAFT,
  APPROVAL_STATUS_APPROVED,
  APPROVAL_STATUS_AWAITED,
  APPROVAL_STATUS_EDITED,
  APPROVAL_STATUS_NEWLY_REJECTED,
  APPROVAL_STATUS_CHANGES_REJECTED
];
